# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Poppy/zmzhang/software/anaconda3/bin/cmake

# The command to remove a file.
RM = /Poppy/zmzhang/software/anaconda3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Poppy/zmzhang/Consensus_Assembly/cLJA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Poppy/zmzhang/Consensus_Assembly/cLJA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Poppy/zmzhang/software/anaconda3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Poppy/zmzhang/software/anaconda3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Poppy/zmzhang/Consensus_Assembly/cLJA/CMakeFiles /Poppy/zmzhang/Consensus_Assembly/cLJA//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Poppy/zmzhang/Consensus_Assembly/cLJA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cLJA

# Build rule for target.
cLJA: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cLJA
.PHONY : cLJA

# fast build rule for target.
cLJA/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/build
.PHONY : cLJA/fast

lib/edlib/src/edlib.o: lib/edlib/src/edlib.cpp.o
.PHONY : lib/edlib/src/edlib.o

# target to build an object file
lib/edlib/src/edlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/lib/edlib/src/edlib.cpp.o
.PHONY : lib/edlib/src/edlib.cpp.o

lib/edlib/src/edlib.i: lib/edlib/src/edlib.cpp.i
.PHONY : lib/edlib/src/edlib.i

# target to preprocess a source file
lib/edlib/src/edlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/lib/edlib/src/edlib.cpp.i
.PHONY : lib/edlib/src/edlib.cpp.i

lib/edlib/src/edlib.s: lib/edlib/src/edlib.cpp.s
.PHONY : lib/edlib/src/edlib.s

# target to generate assembly for a file
lib/edlib/src/edlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/lib/edlib/src/edlib.cpp.s
.PHONY : lib/edlib/src/edlib.cpp.s

src/dbg/dot_graph.o: src/dbg/dot_graph.cpp.o
.PHONY : src/dbg/dot_graph.o

# target to build an object file
src/dbg/dot_graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/dbg/dot_graph.cpp.o
.PHONY : src/dbg/dot_graph.cpp.o

src/dbg/dot_graph.i: src/dbg/dot_graph.cpp.i
.PHONY : src/dbg/dot_graph.i

# target to preprocess a source file
src/dbg/dot_graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/dbg/dot_graph.cpp.i
.PHONY : src/dbg/dot_graph.cpp.i

src/dbg/dot_graph.s: src/dbg/dot_graph.cpp.s
.PHONY : src/dbg/dot_graph.s

# target to generate assembly for a file
src/dbg/dot_graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/dbg/dot_graph.cpp.s
.PHONY : src/dbg/dot_graph.cpp.s

src/dbg/graph_simplification.o: src/dbg/graph_simplification.cpp.o
.PHONY : src/dbg/graph_simplification.o

# target to build an object file
src/dbg/graph_simplification.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/dbg/graph_simplification.cpp.o
.PHONY : src/dbg/graph_simplification.cpp.o

src/dbg/graph_simplification.i: src/dbg/graph_simplification.cpp.i
.PHONY : src/dbg/graph_simplification.i

# target to preprocess a source file
src/dbg/graph_simplification.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/dbg/graph_simplification.cpp.i
.PHONY : src/dbg/graph_simplification.cpp.i

src/dbg/graph_simplification.s: src/dbg/graph_simplification.cpp.s
.PHONY : src/dbg/graph_simplification.s

# target to generate assembly for a file
src/dbg/graph_simplification.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/dbg/graph_simplification.cpp.s
.PHONY : src/dbg/graph_simplification.cpp.s

src/dbg/read_aln.o: src/dbg/read_aln.cpp.o
.PHONY : src/dbg/read_aln.o

# target to build an object file
src/dbg/read_aln.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/dbg/read_aln.cpp.o
.PHONY : src/dbg/read_aln.cpp.o

src/dbg/read_aln.i: src/dbg/read_aln.cpp.i
.PHONY : src/dbg/read_aln.i

# target to preprocess a source file
src/dbg/read_aln.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/dbg/read_aln.cpp.i
.PHONY : src/dbg/read_aln.cpp.i

src/dbg/read_aln.s: src/dbg/read_aln.cpp.s
.PHONY : src/dbg/read_aln.s

# target to generate assembly for a file
src/dbg/read_aln.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/dbg/read_aln.cpp.s
.PHONY : src/dbg/read_aln.cpp.s

src/dbg/run_dbg.o: src/dbg/run_dbg.cpp.o
.PHONY : src/dbg/run_dbg.o

# target to build an object file
src/dbg/run_dbg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/dbg/run_dbg.cpp.o
.PHONY : src/dbg/run_dbg.cpp.o

src/dbg/run_dbg.i: src/dbg/run_dbg.cpp.i
.PHONY : src/dbg/run_dbg.i

# target to preprocess a source file
src/dbg/run_dbg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/dbg/run_dbg.cpp.i
.PHONY : src/dbg/run_dbg.cpp.i

src/dbg/run_dbg.s: src/dbg/run_dbg.cpp.s
.PHONY : src/dbg/run_dbg.s

# target to generate assembly for a file
src/dbg/run_dbg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/dbg/run_dbg.cpp.s
.PHONY : src/dbg/run_dbg.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/multidbg/dot_graph.o: src/multidbg/dot_graph.cpp.o
.PHONY : src/multidbg/dot_graph.o

# target to build an object file
src/multidbg/dot_graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/multidbg/dot_graph.cpp.o
.PHONY : src/multidbg/dot_graph.cpp.o

src/multidbg/dot_graph.i: src/multidbg/dot_graph.cpp.i
.PHONY : src/multidbg/dot_graph.i

# target to preprocess a source file
src/multidbg/dot_graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/multidbg/dot_graph.cpp.i
.PHONY : src/multidbg/dot_graph.cpp.i

src/multidbg/dot_graph.s: src/multidbg/dot_graph.cpp.s
.PHONY : src/multidbg/dot_graph.s

# target to generate assembly for a file
src/multidbg/dot_graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/multidbg/dot_graph.cpp.s
.PHONY : src/multidbg/dot_graph.cpp.s

src/multidbg/graph_io.o: src/multidbg/graph_io.cpp.o
.PHONY : src/multidbg/graph_io.o

# target to build an object file
src/multidbg/graph_io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/multidbg/graph_io.cpp.o
.PHONY : src/multidbg/graph_io.cpp.o

src/multidbg/graph_io.i: src/multidbg/graph_io.cpp.i
.PHONY : src/multidbg/graph_io.i

# target to preprocess a source file
src/multidbg/graph_io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/multidbg/graph_io.cpp.i
.PHONY : src/multidbg/graph_io.cpp.i

src/multidbg/graph_io.s: src/multidbg/graph_io.cpp.s
.PHONY : src/multidbg/graph_io.s

# target to generate assembly for a file
src/multidbg/graph_io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/multidbg/graph_io.cpp.s
.PHONY : src/multidbg/graph_io.cpp.s

src/multidbg/graph_simplification.o: src/multidbg/graph_simplification.cpp.o
.PHONY : src/multidbg/graph_simplification.o

# target to build an object file
src/multidbg/graph_simplification.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/multidbg/graph_simplification.cpp.o
.PHONY : src/multidbg/graph_simplification.cpp.o

src/multidbg/graph_simplification.i: src/multidbg/graph_simplification.cpp.i
.PHONY : src/multidbg/graph_simplification.i

# target to preprocess a source file
src/multidbg/graph_simplification.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/multidbg/graph_simplification.cpp.i
.PHONY : src/multidbg/graph_simplification.cpp.i

src/multidbg/graph_simplification.s: src/multidbg/graph_simplification.cpp.s
.PHONY : src/multidbg/graph_simplification.s

# target to generate assembly for a file
src/multidbg/graph_simplification.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/multidbg/graph_simplification.cpp.s
.PHONY : src/multidbg/graph_simplification.cpp.s

src/multidbg/run_multidbg.o: src/multidbg/run_multidbg.cpp.o
.PHONY : src/multidbg/run_multidbg.o

# target to build an object file
src/multidbg/run_multidbg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/multidbg/run_multidbg.cpp.o
.PHONY : src/multidbg/run_multidbg.cpp.o

src/multidbg/run_multidbg.i: src/multidbg/run_multidbg.cpp.i
.PHONY : src/multidbg/run_multidbg.i

# target to preprocess a source file
src/multidbg/run_multidbg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/multidbg/run_multidbg.cpp.i
.PHONY : src/multidbg/run_multidbg.cpp.i

src/multidbg/run_multidbg.s: src/multidbg/run_multidbg.cpp.s
.PHONY : src/multidbg/run_multidbg.s

# target to generate assembly for a file
src/multidbg/run_multidbg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/multidbg/run_multidbg.cpp.s
.PHONY : src/multidbg/run_multidbg.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cLJA.dir/build.make CMakeFiles/cLJA.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cLJA"
	@echo "... lib/edlib/src/edlib.o"
	@echo "... lib/edlib/src/edlib.i"
	@echo "... lib/edlib/src/edlib.s"
	@echo "... src/dbg/dot_graph.o"
	@echo "... src/dbg/dot_graph.i"
	@echo "... src/dbg/dot_graph.s"
	@echo "... src/dbg/graph_simplification.o"
	@echo "... src/dbg/graph_simplification.i"
	@echo "... src/dbg/graph_simplification.s"
	@echo "... src/dbg/read_aln.o"
	@echo "... src/dbg/read_aln.i"
	@echo "... src/dbg/read_aln.s"
	@echo "... src/dbg/run_dbg.o"
	@echo "... src/dbg/run_dbg.i"
	@echo "... src/dbg/run_dbg.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/multidbg/dot_graph.o"
	@echo "... src/multidbg/dot_graph.i"
	@echo "... src/multidbg/dot_graph.s"
	@echo "... src/multidbg/graph_io.o"
	@echo "... src/multidbg/graph_io.i"
	@echo "... src/multidbg/graph_io.s"
	@echo "... src/multidbg/graph_simplification.o"
	@echo "... src/multidbg/graph_simplification.i"
	@echo "... src/multidbg/graph_simplification.s"
	@echo "... src/multidbg/run_multidbg.o"
	@echo "... src/multidbg/run_multidbg.i"
	@echo "... src/multidbg/run_multidbg.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

